name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'npm dist-tag'
        required: true
        default: 'preview'
      otp:
        description: 'npm 2FA OTP code'
        required: false
        default: ''

permissions:
  contents: read

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        run: |
          if [ -n "${{ github.event.inputs.otp }}" ]; then
            npm publish --access public --tag ${{ github.event.inputs.tag || 'preview' }} --otp="${{ github.event.inputs.otp }}"
          else
            npm publish --access public --tag ${{ github.event.inputs.tag || 'preview' }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
